# -*- coding: utf-8 -*-
"""Task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysYCsEfAdYarSG5Ov0jovH409eu1ejwf
"""



import numpy as np

contacts = []

def add_contact():
    name = input("Enter name: ")
    phone = input("Enter phone number: ")
    email = input("Enter email address: ")
    contacts.append({'name': name, 'phone': phone, 'email': email})
    print("Contact added successfully.")

def view_contacts():
    if not contacts:
        print("No contacts to display.")
    else:
        for idx, contact in enumerate(contacts):
            print(f"Contact {idx + 1}:")
            print(f"Name: {contact['name']}")
            print(f"Phone: {contact['phone']}")
            print(f"Email: {contact['email']}")
            print()

def update_contact():
    view_contacts()
    if not contacts:
        return
    try:
        idx = int(input("Enter index of contact to update: ")) - 1
        if 0 <= idx < len(contacts):
            contacts[idx]['name'] = input("Enter new name: ")
            contacts[idx]['phone'] = input("Enter new phone number: ")
            contacts[idx]['email'] = input("Enter new email address: ")
            print("Contact updated successfully.")
        else:
            print("Invalid index.")
    except ValueError:
        print("Invalid input. Please enter a number.")

def delete_contact():
    view_contacts()
    if not contacts:
        return
    try:
        idx = int(input("Enter index of contact to delete: ")) - 1
        if 0 <= idx < len(contacts):
            del contacts[idx]
            print("Contact deleted successfully.")
        else:
            print("Invalid index.")
    except ValueError:
        print("Invalid input. Please enter a number.")

def main():
    while True:
        print("\nContact Book Menu:")
        print("1. Add Contact")
        print("2. View Contacts")
        print("3. Update Contact")
        print("4. Delete Contact")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            add_contact()
        elif choice == '2':
            view_contacts()
        elif choice == '3':
            update_contact()
        elif choice == '4':
            delete_contact()
        elif choice == '5':
            print("Exiting the program...")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main()